### PR TITLE
Ct_bypass don’t work for arm64e

### PR DESCRIPTION
**Pull request by Toilettrauma**

### CODE REVIEW

**Comment by alfiecg24** [comment]
Please ensure that this still works on a variety of binaries - arm64, arm64e and a fat file with multiple architectures.

**Comment by Toilettrauma** [comment]
Still works. Tested ct_bypass on arm64, arm64e and fat with armv7, arm64, arm64e

**Comment by dhinakg** [comment]
Won't this break `fat_find_preferred_slice`? https://github.com/opa334/ChOma/blob/48942736eff4aab87425bab27f7069fe1a45a3b7/src/Host.c#L38

**Comment by Toilettrauma** [comment]
> Won't this break `fat_find_preferred_slice`?
> 
> https://github.com/opa334/ChOma/blob/48942736eff4aab87425bab27f7069fe1a45a3b7/src/Host.c#L38

Sorry, didn't see it. I removed changes from `src\FAT.c` and moved it to `tests\ct_bypass\main.c`

**Pull request closed without merging**
